defmodule Ema.Intelligence.ToolAtlas do
  @moduledoc """
  Per-tool reliability tracker. Pattern source: OpenKoi "World Model".

  Every tool call (Claude CLI invocation, MCP tool call, Bridge run, ...)
  is recorded with its outcome and duration. Failures are auto-categorized
  into a small set of modes so the resulting atlas can answer:

    - Which tools fail the most?
    - Which tools time out vs. rate-limit vs. error vs. parse-fail?
    - Which tools are getting slower over time?

  The atlas is a single row per `tool_name`. Calls upsert that row and
  update running counters + an EWMA of duration.

  All public functions are best-effort and never raise: if the DB is down
  the call returns `:ok` and logs a warning so callers don't have to
  defensively wrap recording.

  ## Recording

      ToolAtlas.record_call("ema_get_intents", :ok, 142)
      ToolAtlas.record_call("ema_dispatch_execution", {:error, :timeout}, 30_000)

  ## Querying

      ToolAtlas.reliability("ema_get_intents")  # => 0.987
      ToolAtlas.report()                        # markdown string
  """

  import Ecto.Query

  alias Ema.Intelligence.ToolAtlasEntry
  alias Ema.Repo

  require Logger

  @failure_modes ~w(rate_limit timeout auth_error parse_error not_found unknown)a

  @doc """
  Record a tool invocation.

  `result` is one of:
    - `:ok` / `{:ok, _}`           — success
    - `:error` / `{:error, reason}` — failure (reason auto-categorized)
  """
  def record_call(tool_name, result, duration_ms)
      when is_binary(tool_name) and is_integer(duration_ms) do
    try do
      do_record(tool_name, classify(result), duration_ms)
    rescue
      e ->
        Logger.warning("ToolAtlas: record_call failed: #{inspect(e)}")
        :ok
    end
  end

  def record_call(tool_name, result, duration_ms) when is_atom(tool_name),
    do: record_call(Atom.to_string(tool_name), result, duration_ms)

  def record_call(_tool_name, _result, _duration), do: :ok

  @doc "Reliability ratio (success / total). Returns nil if never called."
  def reliability(tool_name) when is_binary(tool_name) do
    case get_entry(tool_name) do
      nil -> nil
      %{total_calls: 0} -> nil
      %{total_calls: total, success_count: succ} -> succ / total
    end
  end

  @doc "Fetch a single tool's stats."
  def get_entry(tool_name) when is_binary(tool_name) do
    Repo.get_by(ToolAtlasEntry, tool_name: tool_name)
  rescue
    _ -> nil
  end

  @doc "List every tool, sorted by reliability ascending (worst first)."
  def list_all do
    Repo.all(from t in ToolAtlasEntry, order_by: [desc: t.total_calls])
  rescue
    _ -> []
  end

  @doc """
  Markdown report sorted by reliability (worst first). Used by SystemBrain
  to project to `vault/system/state/tool-reliability.md`.
  """
  def report do
    entries = list_all()

    body =
      entries
      |> Enum.map(fn e ->
        rel =
          if e.total_calls > 0 do
            "#{Float.round(e.success_count / e.total_calls * 100, 1)}%"
          else
            "—"
          end

        avg = if e.avg_duration_ms, do: "#{e.avg_duration_ms}ms", else: "—"
        modes = format_failure_modes(e.failure_modes)

        last =
          if e.last_called_at,
            do: DateTime.to_iso8601(e.last_called_at),
            else: "never"

        "| `#{e.tool_name}` | #{e.total_calls} | #{rel} | #{avg} | #{modes} | #{last} |"
      end)
      |> Enum.join("\n")

    """
    # Tool Reliability Atlas

    Auto-generated by Ema.Intelligence.ToolAtlas. Do not edit manually.

    | Tool | Calls | Success | Avg ms | Failure Modes | Last Called |
    |------|-------|---------|--------|---------------|-------------|
    #{body}

    ---
    *Tools tracked: #{length(entries)}*
    *Last synced: #{DateTime.utc_now() |> DateTime.to_iso8601()}*
    """
  end

  # ── Internal ──────────────────────────────────────────────────────────────

  defp do_record(tool_name, classification, duration_ms) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)
    entry = get_entry(tool_name) || %ToolAtlasEntry{tool_name: tool_name}

    new_total = (entry.total_calls || 0) + 1
    new_success = (entry.success_count || 0) + if(classification == :success, do: 1, else: 0)

    new_failure =
      (entry.failure_count || 0) + if(classification == :success, do: 0, else: 1)

    new_modes =
      case classification do
        :success ->
          entry.failure_modes || %{}

        {:failure, mode} ->
          modes = entry.failure_modes || %{}
          key = Atom.to_string(mode)
          Map.update(modes, key, 1, &(&1 + 1))
      end

    new_avg = ewma(entry.avg_duration_ms, duration_ms)

    attrs = %{
      tool_name: tool_name,
      total_calls: new_total,
      success_count: new_success,
      failure_count: new_failure,
      failure_modes: new_modes,
      avg_duration_ms: new_avg,
      last_called_at: now
    }

    case Repo.insert_or_update(ToolAtlasEntry.changeset(entry, attrs)) do
      {:ok, saved} ->
        Phoenix.PubSub.broadcast(Ema.PubSub, "tool_atlas", {:tool_atlas, :updated, saved})
        :ok

      {:error, reason} ->
        Logger.warning("ToolAtlas: insert_or_update failed: #{inspect(reason)}")
        :ok
    end
  end

  # Exponentially weighted moving average. First sample seeds the value.
  defp ewma(nil, sample), do: sample
  defp ewma(prev, sample), do: round(prev * 0.8 + sample * 0.2)

  # ── Classification ────────────────────────────────────────────────────────

  defp classify(:ok), do: :success
  defp classify({:ok, _}), do: :success

  defp classify(:error), do: {:failure, :unknown}
  defp classify({:error, reason}), do: {:failure, classify_reason(reason)}
  defp classify(_), do: {:failure, :unknown}

  defp classify_reason(reason) when is_atom(reason), do: pick_mode(reason)
  defp classify_reason(reason) when is_binary(reason), do: pick_mode(reason)

  defp classify_reason(%{code: code, message: msg}) do
    case code do
      :timeout -> :timeout
      :budget_exceeded -> :rate_limit
      :preflight_failed -> :parse_error
      _ -> pick_mode(msg)
    end
  end

  defp classify_reason(%{code: code}) when is_atom(code) do
    case code do
      :timeout -> :timeout
      :budget_exceeded -> :rate_limit
      :preflight_failed -> :parse_error
      _ -> :unknown
    end
  end

  defp classify_reason(_), do: :unknown

  defp pick_mode(value) do
    str = value |> to_string() |> String.downcase()

    cond do
      String.contains?(str, "rate") and String.contains?(str, "limit") -> :rate_limit
      String.contains?(str, "429") -> :rate_limit
      String.contains?(str, "timeout") -> :timeout
      String.contains?(str, "timed out") -> :timeout
      String.contains?(str, "auth") -> :auth_error
      String.contains?(str, "401") -> :auth_error
      String.contains?(str, "403") -> :auth_error
      String.contains?(str, "parse") -> :parse_error
      String.contains?(str, "json") -> :parse_error
      String.contains?(str, "not_found") -> :not_found
      String.contains?(str, "404") -> :not_found
      true -> :unknown
    end
  end

  defp format_failure_modes(nil), do: "—"
  defp format_failure_modes(modes) when modes == %{}, do: "—"

  defp format_failure_modes(modes) when is_map(modes) do
    modes
    |> Enum.sort_by(fn {_k, v} -> -v end)
    |> Enum.map_join(", ", fn {k, v} -> "#{k}:#{v}" end)
  end

  @doc false
  def known_failure_modes, do: @failure_modes
end
