defmodule Ema.SecondBrain.SystemBrain do
  @moduledoc """
  Maintains auto-synced markdown state files in vault/system/state/.
  Subscribes to PubSub events and debounces writes (5 second delay).
  """

  use GenServer
  require Logger

  alias Ema.SecondBrain

  @debounce_ms 5_000

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  # --- Server Callbacks ---

  @impl true
  def init(_opts) do
    Phoenix.PubSub.subscribe(Ema.PubSub, "vault:changes")
    Phoenix.PubSub.subscribe(Ema.PubSub, "projects:changes")
    Phoenix.PubSub.subscribe(Ema.PubSub, "tasks:changes")
    Phoenix.PubSub.subscribe(Ema.PubSub, "proposals:changes")

    # Do initial sync
    send(self(), :sync_all)

    {:ok, %{pending_sync: nil}}
  end

  @impl true
  def handle_info(:sync_all, state) do
    do_sync_all()
    {:noreply, %{state | pending_sync: nil}}
  end

  @impl true
  def handle_info(:debounced_sync, state) do
    do_sync_all()
    {:noreply, %{state | pending_sync: nil}}
  end

  @impl true
  def handle_info(_msg, state) do
    # Any event triggers a debounced sync
    new_state = schedule_debounced_sync(state)
    {:noreply, new_state}
  end

  # --- Private ---

  defp schedule_debounced_sync(state) do
    # Cancel existing timer if present
    if state.pending_sync do
      Process.cancel_timer(state.pending_sync)
    end

    timer = Process.send_after(self(), :debounced_sync, @debounce_ms)
    %{state | pending_sync: timer}
  end

  defp do_sync_all do
    root = SecondBrain.vault_root()
    state_dir = Path.join([root, "system", "state"])
    File.mkdir_p!(state_dir)

    write_projects_state(state_dir)
    write_notes_state(state_dir)

    Logger.debug("SystemBrain: state files synced")
  end

  defp write_projects_state(state_dir) do
    # List all notes in the projects space as a proxy for project tracking
    notes = SecondBrain.list_notes(space: "projects")

    content = """
    # Active Projects

    Auto-generated by EMA SystemBrain. Do not edit manually.

    | Project | Path | Updated |
    |---------|------|---------|
    #{Enum.map_join(notes, "\n", fn n -> "| [[#{n.file_path}]] | `#{n.file_path}` | #{n.updated_at} |" end)}

    ---
    *Last synced: #{DateTime.utc_now() |> DateTime.to_iso8601()}*
    """

    File.write!(Path.join(state_dir, "projects.md"), content)
  end

  defp write_notes_state(state_dir) do
    notes = SecondBrain.list_notes()

    content = """
    # Vault Notes Overview

    Auto-generated by EMA SystemBrain. Do not edit manually.

    **Total notes:** #{length(notes)}

    ## By Space

    #{notes |> Enum.group_by(& &1.space) |> Enum.map_join("\n\n", fn {space, space_notes} ->
      "### #{space || "unorganized"}\n\n#{Enum.map_join(space_notes, "\n", fn n -> "- [[#{n.file_path}]] — #{n.title || "untitled"}" end)}"
    end)}

    ---
    *Last synced: #{DateTime.utc_now() |> DateTime.to_iso8601()}*
    """

    File.write!(Path.join(state_dir, "notes.md"), content)
  end
end
