defmodule Ema.Intents.Schematic.Projector do
  @moduledoc """
  Projects the Intentions Schematic state to a set of read-only markdown
  files under `<vault_root>/wiki/Schematic/`.

  Subscribes to PubSub topic `"schematic:state"` and writes the projection
  on a 5s debounce after each `{:schematic_event, kind}` message.

  An initial projection is scheduled 5s after boot. Use `project_now/0`
  for a manual trigger (cast).

  All sections are guarded with `Code.ensure_loaded?/1` +
  `function_exported?/3` so a missing parallel-wave module degrades
  gracefully (the section's file shows an "unavailable" notice instead
  of crashing the projector).
  """

  use GenServer
  require Logger

  @debounce_ms 5_000
  @initial_delay_ms 5_000
  @topic "schematic:state"

  @auto_header "<!-- AUTO-GENERATED by Ema.Intents.Schematic.Projector — do not edit -->"

  # ── Public API ───────────────────────────────────────────────────

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @doc "Force a projection write immediately (cast)."
  def project_now do
    GenServer.cast(__MODULE__, :project_now)
  end

  # ── GenServer callbacks ──────────────────────────────────────────

  @impl true
  def init(_opts) do
    if Process.whereis(Ema.PubSub) do
      try do
        Phoenix.PubSub.subscribe(Ema.PubSub, @topic)
      rescue
        _ -> :ok
      end
    end

    timer = Process.send_after(self(), :project, @initial_delay_ms)
    {:ok, %{pending: timer}}
  end

  @impl true
  def handle_cast(:project_now, state) do
    state = cancel_pending(state)
    do_project()
    {:noreply, %{state | pending: nil}}
  end

  @impl true
  def handle_info(:project, state) do
    do_project()
    {:noreply, %{state | pending: nil}}
  end

  @impl true
  def handle_info({:schematic_event, _kind}, state) do
    {:noreply, schedule_debounced(state)}
  end

  @impl true
  def handle_info(_msg, state) do
    {:noreply, state}
  end

  # ── Scheduling ───────────────────────────────────────────────────

  defp schedule_debounced(state) do
    state = cancel_pending(state)
    timer = Process.send_after(self(), :project, @debounce_ms)
    %{state | pending: timer}
  end

  defp cancel_pending(%{pending: nil} = state), do: state

  defp cancel_pending(%{pending: timer} = state) do
    Process.cancel_timer(timer)
    %{state | pending: nil}
  end

  # ── Projection ───────────────────────────────────────────────────

  defp do_project do
    try do
      root = vault_root()
      schematic_dir = Path.join([root, "wiki", "Schematic"])

      File.mkdir_p!(Path.join(schematic_dir, "contradictions"))
      File.mkdir_p!(Path.join(schematic_dir, "aspirations"))
      File.mkdir_p!(Path.join(schematic_dir, "clarifications"))
      File.mkdir_p!(Path.join(schematic_dir, "hard-answers"))

      write_index(schematic_dir)
      write_modification_state(schematic_dir)
      write_contradictions(schematic_dir)
      write_aspirations(schematic_dir)
      write_clarifications(schematic_dir)
      write_hard_answers(schematic_dir)

      Logger.debug("Schematic.Projector: wrote projection under #{schematic_dir}")
      :ok
    rescue
      e ->
        Logger.warning("Schematic.Projector: projection failed: #{inspect(e)}")
        :error
    end
  end

  defp vault_root do
    Application.get_env(:ema, :vault_root, Path.expand("~/.local/share/ema/vault"))
  end

  defp now_iso, do: DateTime.utc_now() |> DateTime.to_iso8601()

  # ── Section writers ──────────────────────────────────────────────

  defp write_index(dir) do
    counts = %{
      contradictions_open: safe_count(&list_contradictions/1, status: "open"),
      contradictions_resolved:
        safe_count(&list_contradictions/1, status: "resolved") +
          safe_count(&list_contradictions/1, status: "dismissed"),
      aspirations_stacked: safe_count(&list_aspirations/1, status: "stacked"),
      clarifications_open: safe_count(&list_clarifications/1, status: "open"),
      clarifications_answered: safe_count(&list_clarifications/1, status: "answered"),
      hard_answers_open: safe_count(&list_hard_answers/1, status: "open"),
      hard_answers_answered: safe_count(&list_hard_answers/1, status: "answered")
    }

    content = """
    #{@auto_header}
    # Schematic

    Snapshot of the Intentions Schematic state.

    _Last projected: #{now_iso()}_

    ## Contents

    - [[modification-state]] — current modification toggle state per scope
    - [[contradictions/open]] (#{counts.contradictions_open}) / [[contradictions/resolved-archive]] (#{counts.contradictions_resolved})
    - [[aspirations/stack]] (#{counts.aspirations_stacked})
    - [[clarifications/open]] (#{counts.clarifications_open}) / [[clarifications/answered]] (#{counts.clarifications_answered})
    - [[hard-answers/open]] (#{counts.hard_answers_open}) / [[hard-answers/answered]] (#{counts.hard_answers_answered})
    """

    File.write!(Path.join(dir, "_index.md"), content)
  end

  defp write_modification_state(dir) do
    body =
      if module_available?(Ema.Intents.Schematic.ModificationToggle, :list_states, 0) do
        states =
          try do
            Ema.Intents.Schematic.ModificationToggle.list_states() |> List.wrap()
          rescue
            _ -> []
          end

        rows =
          Enum.map_join(states, "\n", fn s ->
            scope = Map.get(s, :scope_path) || "(global)"
            enabled = if Map.get(s, :enabled, true), do: "yes", else: "no"
            reason = Map.get(s, :disabled_reason) || "—"
            until_ = Map.get(s, :disabled_until) || "—"
            updated = Map.get(s, :updated_by) || "—"
            "| `#{scope}` | #{enabled} | #{reason} | #{until_} | #{updated} |"
          end)

        """
        | Scope | Enabled | Reason | Until | Updated By |
        |-------|---------|--------|-------|------------|
        #{rows}
        """
      else
        "_ModificationToggle module unavailable._"
      end

    content = """
    #{@auto_header}
    # Modification State

    Toggle state for the schematic engine, per scope.

    #{body}

    ---
    _Last projected: #{now_iso()}_
    """

    File.write!(Path.join(dir, "modification-state.md"), content)
  end

  defp write_contradictions(dir) do
    has_mod? = module_available?(Ema.Intents.Schematic.Contradictions, :list, 1)

    open_body =
      if has_mod? do
        list_contradictions(status: "open")
        |> sort_by_severity()
        |> render_contradictions()
      else
        "_Contradictions module unavailable._"
      end

    open = """
    #{@auto_header}
    # Open Contradictions

    Ordered by severity (critical → low).

    #{open_body}

    ---
    _Last projected: #{now_iso()}_
    """

    File.write!(Path.join([dir, "contradictions", "open.md"]), open)

    archived_body =
      if has_mod? do
        resolved = list_contradictions(status: "resolved")
        dismissed = list_contradictions(status: "dismissed")
        render_contradictions(resolved ++ dismissed)
      else
        "_Contradictions module unavailable._"
      end

    archive = """
    #{@auto_header}
    # Resolved & Dismissed Contradictions

    #{archived_body}

    ---
    _Last projected: #{now_iso()}_
    """

    File.write!(Path.join([dir, "contradictions", "resolved-archive.md"]), archive)
  end

  defp write_aspirations(dir) do
    body =
      if module_available?(Ema.Intents.Schematic.Aspirations, :list, 1) do
        list_aspirations(status: "stacked")
        |> Enum.sort_by(&(-(Map.get(&1, :weight) || 0)))
        |> Enum.map_join("\n\n", &render_aspiration/1)
      else
        "_Aspirations module unavailable._"
      end

    content = """
    #{@auto_header}
    # Aspiration Stack

    Stacked aspirations ordered by weight (highest first).

    #{body}

    ---
    _Last projected: #{now_iso()}_
    """

    File.write!(Path.join([dir, "aspirations", "stack.md"]), content)
  end

  defp write_clarifications(dir) do
    write_feed_pair(
      dir,
      "clarifications",
      "Clarifications",
      &list_clarifications/1,
      Ema.Intents.Schematic.Clarifications
    )
  end

  defp write_hard_answers(dir) do
    write_feed_pair(
      dir,
      "hard-answers",
      "Hard Answers",
      &list_hard_answers/1,
      Ema.Intents.Schematic.HardAnswers
    )
  end

  defp write_feed_pair(dir, subdir, label, lister, mod) do
    has_mod? = module_available?(mod, :list, 1)

    open_body =
      if has_mod? do
        lister.(status: "open") |> render_feed_items()
      else
        "_#{inspect(mod)} module unavailable._"
      end

    open = """
    #{@auto_header}
    # Open #{label}

    #{open_body}

    ---
    _Last projected: #{now_iso()}_
    """

    File.write!(Path.join([dir, subdir, "open.md"]), open)

    answered_body =
      if has_mod? do
        lister.(status: "answered") |> render_feed_items()
      else
        "_#{inspect(mod)} module unavailable._"
      end

    answered = """
    #{@auto_header}
    # Answered #{label}

    #{answered_body}

    ---
    _Last projected: #{now_iso()}_
    """

    File.write!(Path.join([dir, subdir, "answered.md"]), answered)
  end

  # ── Renderers ────────────────────────────────────────────────────

  defp render_contradictions([]), do: "_None._"

  defp render_contradictions(list) when is_list(list) do
    Enum.map_join(list, "\n\n", fn c ->
      severity = Map.get(c, :severity) || "medium"
      desc = Map.get(c, :description) || "(no description)"
      scope = Map.get(c, :scope_path) || "—"
      detected = Map.get(c, :detected_by) || "—"
      a = Map.get(c, :intent_a_id) || "—"
      b = Map.get(c, :intent_b_id) || "—"
      id = Map.get(c, :id) || "?"

      """
      ## [#{String.upcase(severity)}] #{desc}

      - **id:** `#{id}`
      - **scope:** `#{scope}`
      - **intents:** `#{a}` ↔ `#{b}`
      - **detected by:** #{detected}
      """
    end)
  end

  defp render_aspiration(a) do
    title = Map.get(a, :title) || "(untitled)"
    horizon = Map.get(a, :horizon) || "long"
    weight = Map.get(a, :weight) || 0
    scope = Map.get(a, :scope_path) || "—"
    desc = Map.get(a, :description) || ""
    tags = Map.get(a, :tags) || []
    id = Map.get(a, :id) || "?"

    tag_str = if tags == [], do: "—", else: Enum.join(tags, ", ")

    """
    ## #{title} _(weight #{weight}, #{horizon})_

    - **id:** `#{id}`
    - **scope:** `#{scope}`
    - **tags:** #{tag_str}

    #{desc}
    """
  end

  defp render_feed_items([]), do: "_None._"

  defp render_feed_items(list) when is_list(list) do
    Enum.map_join(list, "\n\n---\n\n", &render_feed_item/1)
  end

  defp render_feed_item(item) do
    title = Map.get(item, :title) || "(untitled)"
    id = Map.get(item, :id) || "?"
    scope = Map.get(item, :scope_path) || "—"
    context = Map.get(item, :context) || ""
    options = Map.get(item, :options) || %{}
    selected = Map.get(item, :selected) || []
    response = Map.get(item, :user_response)
    resolution = Map.get(item, :resolution)

    options_md = render_options(options)

    selected_md =
      case selected do
        [] -> ""
        list -> "\n**Selected:** #{Enum.join(list, ", ")}\n"
      end

    response_md = if response, do: "\n**Response:** #{response}\n", else: ""
    resolution_md = if resolution, do: "\n**Resolution:** #{resolution}\n", else: ""

    """
    # #{title}

    - **id:** `#{id}`
    - **scope:** `#{scope}`

    #{context}

    #{options_md}#{selected_md}#{response_md}#{resolution_md}
    """
  end

  # ABCD123 options: %{"A" => %{"label" => "...", "variants" => %{"1" => "...", ...}}, ...}
  # Render flexibly — also handle simpler shapes (string→string, string→list).
  defp render_options(options) when is_map(options) and map_size(options) == 0, do: ""

  defp render_options(options) when is_map(options) do
    options
    |> Enum.sort_by(fn {k, _} -> to_string(k) end)
    |> Enum.map_join("\n\n", fn {key, value} -> render_option(key, value) end)
  end

  defp render_options(_), do: ""

  defp render_option(key, %{"label" => label, "variants" => variants})
       when is_map(variants) do
    variant_lines =
      variants
      |> Enum.sort_by(fn {k, _} -> to_string(k) end)
      |> Enum.map_join("\n", fn {n, v} -> "  - #{n}: #{v}" end)

    "## #{key}: #{label}\n#{variant_lines}"
  end

  defp render_option(key, value) when is_map(value) do
    label = Map.get(value, "label") || Map.get(value, :label) || ""
    rest = Map.drop(value, ["label", :label])

    inner =
      rest
      |> Enum.map_join("\n", fn {k, v} -> "  - #{k}: #{inspect(v)}" end)

    "## #{key}: #{label}\n#{inner}"
  end

  defp render_option(key, value) when is_list(value) do
    lines = Enum.with_index(value, 1) |> Enum.map_join("\n", fn {v, i} -> "  - #{i}: #{v}" end)
    "## #{key}\n#{lines}"
  end

  defp render_option(key, value) do
    "## #{key}\n  - #{value}"
  end

  defp sort_by_severity(list) do
    order = %{"critical" => 0, "high" => 1, "medium" => 2, "low" => 3}
    Enum.sort_by(list, fn c -> Map.get(order, Map.get(c, :severity) || "medium", 9) end)
  end

  # ── Safe module-call helpers ─────────────────────────────────────

  defp module_available?(mod, fun, arity) do
    Code.ensure_loaded?(mod) and function_exported?(mod, fun, arity)
  end

  defp list_contradictions(opts) do
    if module_available?(Ema.Intents.Schematic.Contradictions, :list, 1) do
      try do
        Ema.Intents.Schematic.Contradictions.list(opts) |> List.wrap()
      rescue
        _ -> []
      end
    else
      []
    end
  end

  defp list_aspirations(opts) do
    if module_available?(Ema.Intents.Schematic.Aspirations, :list, 1) do
      try do
        Ema.Intents.Schematic.Aspirations.list(opts) |> List.wrap()
      rescue
        _ -> []
      end
    else
      []
    end
  end

  defp list_clarifications(opts) do
    if module_available?(Ema.Intents.Schematic.Clarifications, :list, 1) do
      try do
        Ema.Intents.Schematic.Clarifications.list(opts) |> List.wrap()
      rescue
        _ -> []
      end
    else
      []
    end
  end

  defp list_hard_answers(opts) do
    if module_available?(Ema.Intents.Schematic.HardAnswers, :list, 1) do
      try do
        Ema.Intents.Schematic.HardAnswers.list(opts) |> List.wrap()
      rescue
        _ -> []
      end
    else
      []
    end
  end

  defp safe_count(fun, opts) do
    try do
      fun.(opts) |> length()
    rescue
      _ -> 0
    end
  end
end
