/**
 * Run-ID generator.
 *
 * Format: `YYYYMMDDTHHMMSSsssZ-<slug>`, e.g. `20260412T143059123Z-k7f3pq`.
 *
 * - ISO-ish prefix keeps directories sorted lexicographically by compile time.
 * - Random slug avoids collisions when two compiles land in the same millisecond.
 * - Safe characters only: no path separators, no shell metacharacters.
 */

import { randomBytes } from 'node:crypto';

const SLUG_ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789';
const SLUG_LENGTH = 6;

function timestampPrefix(now: Date): string {
  // 2026-04-12T14:30:59.123Z  ->  20260412T143059123Z
  return now.toISOString().replace(/[-:.]/g, '');
}

function randomSlug(length: number): string {
  const bytes = randomBytes(length);
  let out = '';
  for (let i = 0; i < length; i += 1) {
    const byte = bytes[i] ?? 0;
    out += SLUG_ALPHABET[byte % SLUG_ALPHABET.length];
  }
  return out;
}

export function generateRunId(now: Date = new Date()): string {
  return `${timestampPrefix(now)}-${randomSlug(SLUG_LENGTH)}`;
}

/**
 * Returns true if the string looks like a run ID generated by `generateRunId`.
 * Used by `Composer.list()` to ignore stray files/directories under the
 * artifacts root.
 */
export function isRunId(value: string): boolean {
  return /^\d{8}T\d{9}Z-[a-z0-9]{6}$/.test(value);
}
